spring:
    datasource:
      driverClassName: org.postgresql.Driver
      password: admin
      url: jdbc:postgresql://localhost:5432/car_wash
      username: admin

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL82Dialect
    mvc:
      hiddenmethod:
        filter:
          enabled: true

    flyway:
      baseline-on-migrate: true